User.create! [
	{name: "Foo",
	email: "Foo@gmail.com",
	password: "password",
	location: "San Francisco"},
	{name: "Tex",
	email: "tex@gmail.com",
	password: "password",
	location: "Austin"},
	{name: "Pierre",
	email: "pierre@gmail.com",
	password: "password",
	location: "Aix-en-Provence"},
	{name: "Meathead",
	email: "meat.head@gmail.com",
	password: "password",
	location: "Brooklyn"},
	{name: "Fathead",
	email: "fat.head@gmail.com",
	password: "password",
	location: "Brooklyn"},
	]

Equipment.create! [
	{user_id: 1,
	typ: 'bass',
	make: 'Kay',
	info: 'Rotocore strings, K&K Bass Master  Rockabilly pickup'},
	{user_id: 1,
	typ: 'head',
	make: 'Fender',
	info: 'TB1200'},
	{user_id: 1,
	typ: 'cab',
	make: 'Fender',
	info: '8x10'},
	{user_id: 2,
	typ: 'bass',
	make: 'Strunal',
	info: '50/1'},
	{user_id: 3,
	typ: 'bass',
	make: 'Engelhardt',
	info: 'painted black with house paint'},
	{user_id: 4,
	typ: 'head',
	make: 'Ashdown',
	info: 'MAG300'},
	{user_id: 4,
	typ: 'cab',
	make: 'Ashdown',
	info: '4x8'},
	{user_id: 4,
	typ: 'cab',
	make: 'Ashdown',
	info: '4x8'},
	{user_id: 2,
	typ: 'cab',
	make: 'Ashdown',
	info: '4x8'},
	{user_id: 3,
	typ: 'cab',
	make: 'Ashdown',
	info: '4x8'},
	{user_id: 5,
	typ: 'cab',
	make: 'Ashdown',
	info: '4x8'},
	{user_id: 3,
	typ: 'bass',
	make: 'Engelnarot',
	info: 'from goodwill'},
	]
